//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMAUG.Edmx
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SMAUGEntities : DbContext
    {
        public SMAUGEntities()
            : base("name=SMAUGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Arda> Arda { get; set; }
        public virtual DbSet<Item> Item { get; set; }
        public virtual DbSet<Person> Person { get; set; }
        public virtual DbSet<Publication> Publication { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
